---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bmh-label-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bmh-label-controller
  template:
    metadata:
      labels:
        name: bmh-label-controller
    spec:
      serviceAccountName: bmh-label-controller
      containers:
        - name: bmh-label-controller
          # Replace this with the built image name
          image: "REPLACE_IMAGE"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "bmh-label-controller"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
